### ISSUE TITLE
F48: Mensaje pantalla en blanco (feedback 8)

### ISSUE THREAD

**Issue by mpadillatabuenca** [JStockwell/ISPP-G9-22-23#209]

**Comment by alvaro-us** [comment]
Al iniciar sesión, en las pestañas que no tienen ninguna entrada creada, simplemente sale en blanco. Se podría poner que un textito que indicara que ahora mismo esa sección está vacía y que puede añadir alguna pulsando abajo, para que no de lugar a confusión, ya que el usuario podría pensar que la aplicación se ha quedado pillada o que está cargando.
